name: Project_feedback

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd project
          pip install --upgrade pip
          pip install pandas
          pip install SQLAlchemy
          pip install kaggle
          pip install matplotlib
          pip install seaborn
          pip install simplejson
          pip install reportlab

      - name: Set Kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          echo "Kaggle credentials set."

      - name: Run tests
        run: |
          cd project
          ./tests.sh
